services:
  - type: web
    name: sanivor-offers
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
    healthCheckPath: /

databases:
  - name: sanivor-db
    plan: free
    databaseName: sanivor
    user: sanivor_user
