<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ElementSeeder extends Seeder
{
    public function run(): void
    {
        $elements = [
            ['name' => 'Wand-WC für AP-Spühlkasten', 'quantity' => 1],
            ['name' => 'Waschtisch', 'quantity' => 1],
            ['name' => 'Doppel-WT', 'quantity' => 1],
            ['name' => 'Behinderten-WT ohne Siphon', 'quantity' => 1],
            ['name' => 'Behinderten-Wt. mit Siphon', 'quantity' => 1],
            ['name' => 'Bidet', 'quantity' => 1],
            ['name' => 'Küche', 'quantity' => 1],
            ['name' => 'Waschmaschine onhe UP Siphon', 'quantity' => 1],
            ['name' => 'Waschmaschine mit UP Siphon (Rohbau Set)', 'quantity' => 1],
            ['name' => 'Wand-WC-Element UP 320, Typ 112', 'quantity' => 1],
            ['name' => 'Abzweriger 88 1/2° 110/110 mm', 'quantity' => 1],
            ['name' => 'Wand-WC-Element UP320, Duofresh, Typ 112', 'quantity' => 1],
            ['name' => 'Wand-WC-Element UP320, Typ 112, Geruchsabsaugeanschluss', 'quantity' => 1],
            ['name' => 'Wand-WC-Element UP200, Omega, Typ 85', 'quantity' => 1],
            ['name' => 'Wand-WC-Element UP200, Omega, Typ 98', 'quantity' => 1],
            ['name' => 'Wand-WC-Element UP200, Omega, Typ 114', 'quantity' => 1],
            ['name' => 'Badewanne AP 153', 'quantity' => 1],
            ['name' => 'Bad AP 153 mit Gleitstange', 'quantity' => 1],
            ['name' => 'Bad AP 153 mit Gleitstange und Glasstrenwand', 'quantity' => 1],
            ['name' => 'Bad UP', 'quantity' => 1],
            ['name' => 'Bad UP mit Gleitstange und Handbrause', 'quantity' => 1],
            ['name' => 'Bad UP mit Gleitstange, Handbrause und Kopfbrause', 'quantity' => 1],
            ['name' => 'Bad UP mit Gleitstange, Handbrause, Kopfbrause und Glasstrenwand', 'quantity' => 1],
            ['name' => 'Dusche AP 153', 'quantity' => 1],
            ['name' => 'Dusche AP 153 mit Gleitstange', 'quantity' => 1],
            ['name' => 'Dusche AP 153 mit Gleitstange und Glasstrenwand', 'quantity' => 1],
            ['name' => 'Dusche UP', 'quantity' => 1],
            ['name' => 'Dusche UP mit Gleitstange und Handbrause', 'quantity' => 1],
            ['name' => 'Dusche UP mit Gleitstange, Handbrause und Kopfbrause', 'quantity' => 1],
            ['name' => 'Dusche UP mit Gleitstange, Handbrause, Kopfbrause und Glasstrenwand', 'quantity' => 1],
            ['name' => 'Geberit Urinal 137cm', 'quantity' => 1],
            ['name' => 'Geberit Urinal 114cm', 'quantity' => 1],
            ['name' => 'Geberit Urinal Universal 114cm', 'quantity' => 1],
            ['name' => 'Geberit Urinal 123cm', 'quantity' => 1],
            ['name' => 'Urinal ohne steurung mit wasseranschl.', 'quantity' => 1],
            ['name' => 'Urinal 0 Liter', 'quantity' => 1],
            ['name' => 'Holz für Küchenkombination', 'quantity' => 1],
            ['name' => 'Bogenabzweig 88 1/2° 110/110mm', 'quantity' => 1],
            ['name' => 'Mehrfachabzweig 3-teilig 110/110mm', 'quantity' => 1],
            ['name' => 'Doppel-Abzweig 180° 110/110mm', 'quantity' => 1],
            ['name' => 'Abzweriger 88 1/2° 125/110mm', 'quantity' => 1],
            ['name' => 'Doppel-Abzweig 180° 125/110mm', 'quantity' => 1],
            ['name' => 'Mehrfachabzweig 3-teilig 135° 125/110mm', 'quantity' => 1],
            ['name' => 'Bogenabzweig 88 1/2° 110mm (Silent)', 'quantity' => 1],
            ['name' => 'Doppel-Abzweig 180° (L/R)110mm (310.171 / 172) (Silent)', 'quantity' => 1],
            ['name' => 'Doppel-Abzweig 110mm (Silent)', 'quantity' => 1],
            ['name' => 'Abzweig 88 1/2° 135/110mm (Silent)', 'quantity' => 1],
            ['name' => '56mm Umlüftung PE', 'quantity' => 1],
            ['name' => '63mm Umlüftung PE', 'quantity' => 1],
            ['name' => '75mm Umlüftung PE', 'quantity' => 1],
            ['name' => '90mm Umlüftung PE', 'quantity' => 1],
            ['name' => '110mm Umlüftung PE', 'quantity' => 1],
            ['name' => '56 mm Umlüftung Silent', 'quantity' => 1],
            ['name' => '63mm Umlüftung Silent', 'quantity' => 1],
            ['name' => '75mm Umlüftung Silent', 'quantity' => 1],
            ['name' => '90mm Umlüftung Silent', 'quantity' => 1],
            ['name' => '110mm Umlüftung Silent', 'quantity' => 1],
            ['name' => 'Apparate Anschl. in PE-Silent', 'quantity' => 1],
            ['name' => 'Apparate Anschl. in PE', 'quantity' => 1],
            ['name' => 'Steigleitungen CNS', 'quantity' => 1],
            ['name' => 'Rehau 16mm', 'quantity' => 1],
            ['name' => 'Rehau 20mm', 'quantity' => 1],
            ['name' => 'Sanipex 16mm', 'quantity' => 1],
            ['name' => 'Sanipex 20mm', 'quantity' => 1],
            ['name' => 'Nussbaum 16mm', 'quantity' => 1],
            ['name' => 'Nussbaum 20mm', 'quantity' => 1],
            ['name' => 'Sanipex 16mm', 'quantity' => 1],
            ['name' => 'Sanipex 20mm', 'quantity' => 1],
            ['name' => 'iFit 16/20mm', 'quantity' => 1],
            ['name' => 'Nussbaum 16mm', 'quantity' => 1],
            ['name' => 'KQ-Compaq small Absperrventile 3/4"  mit 2 Zählergehäuse Koax 2" (ohne Abdeckung - Rosette)', 'quantity' => 1],
            ['name' => 'Freistehend Austock', 'quantity' => 1],
            ['name' => 'Vorwand Aufstock', 'quantity' => 1],
            ['name' => 'Nussbaum 20mm', 'quantity' => 1],
            ['name' => 'Kompakteinheit, Absperrventile 3/4" 1 Zählergehäuse Koax 2"', 'quantity' => 1],
            ['name' => 'Kompakteinheit, Absperrventile 3/4" 2 Zählergehäuse Koax 2"', 'quantity' => 1],
            ['name' => 'Kompakteinheit, Absperrventile 3/4" Ohne Zählergehäuse', 'quantity' => 1],
            ['name' => 'Nische Ca 50cmx30cm (für Dusche/Bad)', 'quantity' => 1],
            ['name' => 'Nische für Spiegelschrank 80cm x 80cm', 'quantity' => 1],
            ['name' => 'Freistehend Aufstock mit Seiten-Abschl.', 'quantity' => 1],
            ['name' => 'Vorwand Aufstock mit Seiten-Abschl.', 'quantity' => 1],
            ['name' => 'Vorwand Grundrahme', 'quantity' => 1],
            ['name' => 'Vorwand Grundrahme Teilhoch', 'quantity' => 1],
            ['name' => 'Vorwand Grundrahme Telihoch und Rahmhoch', 'quantity' => 1],
            ['name' => 'Freistehend Grundrahme', 'quantity' => 1],
            ['name' => 'Freistehend Grundrahme Hinten leer', 'quantity' => 1],
            ['name' => 'Nische für Spiegelschrank 120cm x 80cm', 'quantity' => 1],
            ['name' => 'Nische für Spiegelschrank 90cm x 60cm', 'quantity' => 1],
            ['name' => 'Waschtisch UP', 'quantity' => 1],
            ['name' => 'Isoliert mit schwer Schallschutzmatte', 'quantity' => 1],
            ['name' => 'Dusche UP mit Gleitstange, Handbrause und Glasstrenwand', 'quantity' => 1],
            ['name' => 'Holz Einlage', 'quantity' => 1],
            ['name' => 'Deckeneinlagen WAS', 'quantity' => 1],
            ['name' => 'Vorwand Grundelement DeBo', 'quantity' => 1],
            ['name' => 'Vorwand Aufstockelement DeBo', 'quantity' => 1],
            ['name' => 'Trennwand Grundelement DeBo', 'quantity' => 1],
            ['name' => 'Trennwand Aufstockelement DeBo', 'quantity' => 1],
            ['name' => 'Waschtisch (ohne Einbaumöbel)', 'quantity' => 1],
            ['name' => 'GF-JRG UP-Absperr-/Zählereiheit kompakt 3/4\'\' -PN', 'quantity' => 1],
            ['name' => 'Lüftungsgehäuse (Lieferung bauseits)', 'quantity' => 1],
            ['name' => 'FS WAR 90 Silent', 'quantity' => 1],
            ['name' => 'FS WAR 110 Silent', 'quantity' => 1],
            ['name' => 'Rohrschelle', 'quantity' => 1],
            ['name' => 'Fallstrang Umlenkung Geberit Isol.', 'quantity' => 1],
            ['name' => 'Deckeneinlagen WAR', 'quantity' => 1],
            ['name' => 'Inkl. Rohrschelle', 'quantity' => 1],
            ['name' => 'Inkl. E-Muffen', 'quantity' => 1],
            ['name' => 'Inkl. Schalungsschoner', 'quantity' => 1],
            ['name' => 'Inkl. Kanisparblöck', 'quantity' => 1],
            ['name' => 'Kanalisation', 'quantity' => 1],
        ];

        foreach ($elements as $element) {
            DB::table('elements')->insert([
                'name' => \$element['name'],
                'quantity' => \$element['quantity'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}