<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialPieceSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [];
        $rows[] = ['name' => 'WC AP 95 Piece', 'price_in' => 138.88, 'price_out' => 217.0];
        $rows[] = ['name' => 'Waschtisch Piece', 'price_in' => 42.94, 'price_out' => 64.5];
        $rows[] = ['name' => 'Behinderten-Wt. ohne Siphon Piece', 'price_in' => 31.4, 'price_out' => 100.0];
        $rows[] = ['name' => 'Dusche AP 153 Piece', 'price_in' => 27.6, 'price_out' => 47.2];
        $rows[] = ['name' => 'Bidet Piece', 'price_in' => 41.0, 'price_out' => 170.0];
        $rows[] = ['name' => 'Küche Piece', 'price_in' => 29.0, 'price_out' => 58.5];
        $rows[] = ['name' => 'WM ohne Siphon Piece', 'price_in' => 24.0, 'price_out' => 60.0];
        $rows[] = ['name' => 'WM mit Siphon Piece', 'price_in' => 39.0, 'price_out' => 97.5];
        $rows[] = ['name' => 'Befestigung Piece', 'price_in' => 2.15, 'price_out' => 5.3];
        $rows[] = ['name' => 'UP320, Typ 112 Piece', 'price_in' => 116.0, 'price_out' => 156.0];
        $rows[] = ['name' => 'UP320, Duofresh, Typ 112 Piece', 'price_in' => 144.0, 'price_out' => 224.0];
        $rows[] = ['name' => 'UP320, Typ 112, Geruchsabsaugeanschluss Piece', 'price_in' => 140.8, 'price_out' => 220.0];
        $rows[] = ['name' => 'UP200, Omega, Typ 85 Piece', 'price_in' => 143.36, 'price_out' => 224.0];
        $rows[] = ['name' => 'UP200, Omega, Typ 98 Piece', 'price_in' => 143.36, 'price_out' => 224.0];
        $rows[] = ['name' => 'UP200, Omega, Typ 114 Piece', 'price_in' => 143.36, 'price_out' => 224.0];
        $rows[] = ['name' => 'Behinderten-Wt. mit Siphon Piece', 'price_in' => 49.4, 'price_out' => 130.0];
        $rows[] = ['name' => 'Bad AP 153 Piece', 'price_in' => 27.6, 'price_out' => 47.2];
        $rows[] = ['name' => 'Gleitstange Piece', 'price_in' => 10.0, 'price_out' => 28.0];
        $rows[] = ['name' => 'Glasstrenwand Piece', 'price_in' => 14.0, 'price_out' => 32.2];
        $rows[] = ['name' => 'Bad UP Piece', 'price_in' => 10.0, 'price_out' => 40.7];
        $rows[] = ['name' => 'Kopfbrause Piece', 'price_in' => 15.0, 'price_out' => 32.2];
        $rows[] = ['name' => 'Handbrause Piece', 'price_in' => 14.0, 'price_out' => 32.2];
        $rows[] = ['name' => 'Holz (Sperrholz) 24 mm fur Gleitstange Piece', 'price_in' => 4.0, 'price_out' => 22.0];
        $rows[] = ['name' => 'Holz (Sperrholz) 24 mm fur Glasstrenwande Piece', 'price_in' => 4.0, 'price_out' => 22.0];
        $rows[] = ['name' => 'Div. Holz einlagen Piece', 'price_in' => 6.0, 'price_out' => 28.0];
        $rows[] = ['name' => 'Dusche UP Piece', 'price_in' => 10.0, 'price_out' => 40.7];
        $rows[] = ['name' => 'Geberit Urinal 137cm Piece', 'price_in' => 342.0, 'price_out' => 483.0];
        $rows[] = ['name' => 'Geberit Urinal Universal 114cm Piece', 'price_in' => 198.4, 'price_out' => 310.0];
        $rows[] = ['name' => 'Geberit Urinal 114cm Piece', 'price_in' => 208.0, 'price_out' => 325.0];
        $rows[] = ['name' => 'Geberit Urinal 123cm Piece', 'price_in' => 196.48, 'price_out' => 307.0];
        $rows[] = ['name' => 'Urinal ohne steurung mit wasseranschl. Piece', 'price_in' => 28.0, 'price_out' => 275.0];
        $rows[] = ['name' => 'Urinal 0 Liter Piece', 'price_in' => 17.0, 'price_out' => 240.0];
        $rows[] = ['name' => 'Holz fur Küchenkombination Piece', 'price_in' => 4.0, 'price_out' => 20.0];
        $rows[] = ['name' => 'Geberit PE Langmuffe 110 mm Piece', 'price_in' => 5.5, 'price_out' => 8.6];
        $rows[] = ['name' => 'Geberit PE Langmuffe 125 mm Piece', 'price_in' => 11.46, 'price_out' => 17.9];
        $rows[] = ['name' => 'Geberit PE Abzweig 88 1/2° 110/110 mm Piece', 'price_in' => 5.18, 'price_out' => 8.1];
        $rows[] = ['name' => 'Geberit PE Bogenabzweig 88 1/2° 110/110 mm Piece', 'price_in' => 6.4, 'price_out' => 10.0];
        $rows[] = ['name' => 'Geberit PE Mehrfachabzweig 3-teilig 110/110 mm Piece', 'price_in' => 26.5, 'price_out' => 41.4];
        $rows[] = ['name' => 'Geberit PE Doppel-Abzweig 180° 110/110 mm Piece', 'price_in' => 20.29, 'price_out' => 31.7];
        $rows[] = ['name' => 'Geberit PE Doppel-Abzweig 180° 125/110 mm Piece', 'price_in' => 24.64, 'price_out' => 38.5];
        $rows[] = ['name' => 'Geberit PE Mehrfachabzweig 3-teilig 135° 125/110 mm Piece', 'price_in' => 32.0, 'price_out' => 50.0];
        $rows[] = ['name' => 'Rohrschelle 125 mm Piece', 'price_in' => 14.5, 'price_out' => 20.0];
        $rows[] = ['name' => 'Rohrschelle 135 mm Piece', 'price_in' => 6.55, 'price_out' => 11.3];
        $rows[] = ['name' => 'Geberit PE Rohr 110 mm Piece', 'price_in' => 5.61, 'price_out' => 11.0];
        $rows[] = ['name' => 'Geberit PE Rohr 125 mm Piece', 'price_in' => 7.85, 'price_out' => 15.4];
        $rows[] = ['name' => 'Geberit PE Abzweig 88 1/2° 125/110 mm Piece', 'price_in' => 10.18, 'price_out' => 15.9];
        $rows[] = ['name' => 'Geberit Silent Rohr 110 mm Piece', 'price_in' => 14.47, 'price_out' => 22.9];
        $rows[] = ['name' => 'Geberit Silent Rohr 135 mm Piece', 'price_in' => 13.42, 'price_out' => 25.8];
        $rows[] = ['name' => 'Geberit Silent Bogenabzweig 88 1/2° 110 mm Piece', 'price_in' => 11.53, 'price_out' => 17.7];
        $rows[] = ['name' => 'Geberit Silent Doppel-Abzweig 180° (L/R)110 mm (310.171 / 172) Piece', 'price_in' => 60.5, 'price_out' => 92.5];
        $rows[] = ['name' => 'Geberit Silent Doppel-Abzweig 180° 110 mm Piece', 'price_in' => 28.54, 'price_out' => 49.2];
        $rows[] = ['name' => 'Geberit Silent Langmuffe 110 mm Piece', 'price_in' => 12.5, 'price_out' => 19.5];
        $rows[] = ['name' => 'Geberit Silent Langmuffe 135 mm Piece', 'price_in' => 20.47, 'price_out' => 35.3];
        $rows[] = ['name' => 'Geberit Rohrschelle Fixpunkt Piece', 'price_in' => 11.6, 'price_out' => 20.0];
        $rows[] = ['name' => 'Geberit Silent Abzweig 88 1/2° 135/110 mm Piece', 'price_in' => 16.76, 'price_out' => 28.9];
        $rows[] = ['name' => 'Geberit PE Bogen 45° 110 mm Piece', 'price_in' => 9.2, 'price_out' => 14.4];
        $rows[] = ['name' => 'Geberit PE Bogen 45° 56 mm Piece', 'price_in' => 1.54, 'price_out' => 2.4];
        $rows[] = ['name' => 'Geberit PE Bogen 45° 63 mm Piece', 'price_in' => 1.73, 'price_out' => 2.7];
        $rows[] = ['name' => 'Geberit PE Bogen 45° 75 mm Piece', 'price_in' => 2.62, 'price_out' => 4.1];
        $rows[] = ['name' => 'Geberit PE Bogen 45° 90 mm Piece', 'price_in' => 3.2, 'price_out' => 5.0];
        $rows[] = ['name' => 'Geberit PE Reduktion zentrich 110/56 mm Piece', 'price_in' => 4.93, 'price_out' => 7.7];
        $rows[] = ['name' => 'Geberit PE Reduktion zentrich 110/63 mm Piece', 'price_in' => 4.93, 'price_out' => 7.7];
        $rows[] = ['name' => 'Geberit PE Reduktion zentrich 110/75 mm Piece', 'price_in' => 6.27, 'price_out' => 9.8];
        $rows[] = ['name' => 'Geberit PE Reduktion zentrich 110/90 mm Piece', 'price_in' => 6.27, 'price_out' => 9.8];
        $rows[] = ['name' => 'Geberit PE Elektromuffe mit Indikator 56 mm Piece', 'price_in' => 2.62, 'price_out' => 4.1];
        $rows[] = ['name' => 'Geberit PE Elektromuffe mit Indikator 63 mm Piece', 'price_in' => 2.75, 'price_out' => 4.3];
        $rows[] = ['name' => 'Geberit PE Elektromuffe mit Indikator 75 mm Piece', 'price_in' => 2.88, 'price_out' => 4.5];
        $rows[] = ['name' => 'Geberit PE Elektromuffe mit Indikator 90 mm Piece', 'price_in' => 3.01, 'price_out' => 4.7];
        $rows[] = ['name' => 'Geberit PE Elektromuffe mit Indikator 110 mm Piece', 'price_in' => 3.58, 'price_out' => 5.6];
        $rows[] = ['name' => 'Geberit PE Rohr im Stangen 56 mm Piece', 'price_in' => 2.04, 'price_out' => 4.0];
        $rows[] = ['name' => 'Geberit PE Rohr im Stangen 63 mm Piece', 'price_in' => 2.142, 'price_out' => 4.2];
        $rows[] = ['name' => 'Geberit PE Rohr im Stangen 75 mm Piece', 'price_in' => 2.84, 'price_out' => 5.8];
        $rows[] = ['name' => 'Geberit PE Rohr im Stangen 90 mm Piece', 'price_in' => 4.8, 'price_out' => 10.0];
        $rows[] = ['name' => 'Geberit PE Rohr im Stangen 110 mm Piece', 'price_in' => 5.61, 'price_out' => 11.0];
        $rows[] = ['name' => 'Geberit Silent Rohr im Stangen 56 mm Piece', 'price_in' => 5.2, 'price_out' => 10.0];
        $rows[] = ['name' => 'Geberit Silent Rohr im Stangen 63 mm Piece', 'price_in' => 5.67, 'price_out' => 10.9];
        $rows[] = ['name' => 'Geberit Silent Rohr im Stangen 75 mm Piece', 'price_in' => 7.38, 'price_out' => 14.2];
        $rows[] = ['name' => 'Geberit Silent Rohr im Stangen 90 mm Piece', 'price_in' => 11.07, 'price_out' => 21.3];
        $rows[] = ['name' => 'Geberit Silent Reduktion zentrich 110/56 mm Piece', 'price_in' => 5.57, 'price_out' => 9.6];
        $rows[] = ['name' => 'Geberit Silent Reduktion zentrich 110/63 mm Piece', 'price_in' => 5.51, 'price_out' => 9.5];
        $rows[] = ['name' => 'Geberit Silent Reduktion zentrich 110/75 mm Piece', 'price_in' => 5.57, 'price_out' => 9.6];
        $rows[] = ['name' => 'Geberit Silent Bogen 45° 56 mm Piece', 'price_in' => 2.96, 'price_out' => 5.1];
        $rows[] = ['name' => 'Geberit Silent Bogen 45° 63 mm Piece', 'price_in' => 2.97, 'price_out' => 5.6];
        $rows[] = ['name' => 'Geberit Silent Bogen 45° 75 mm Piece', 'price_in' => 3.65, 'price_out' => 6.3];
        $rows[] = ['name' => 'Geberit Silent Bogen 45° 90 mm Piece', 'price_in' => 6.03, 'price_out' => 10.4];
        $rows[] = ['name' => 'Geberit Silent Bogen 45° 110 mm Piece', 'price_in' => 5.78, 'price_out' => 10.7];
        $rows[] = ['name' => 'Geberit Silent Abzweig 45° 110 mm Piece', 'price_in' => 9.56, 'price_out' => 17.7];
        $rows[] = ['name' => 'Geberit Silent Abzweig 45° 110/56 mm Piece', 'price_in' => 10.27, 'price_out' => 17.7];
        $rows[] = ['name' => 'Geberit Silent Abzweig 45° 110/63 mm Piece', 'price_in' => 10.27, 'price_out' => 17.7];
        $rows[] = ['name' => 'Geberit Silent Abzweig 45° 110/75 mm Piece', 'price_in' => 10.27, 'price_out' => 17.7];
        $rows[] = ['name' => 'Geberit Silent Abzweig 45° 110/90 mm Piece', 'price_in' => 10.27, 'price_out' => 17.7];
        $rows[] = ['name' => 'Silent Apparate (anschl.) Piece', 'price_in' => 36.0, 'price_out' => 57.0];
        $rows[] = ['name' => 'PE Apparate (anschl.) Piece', 'price_in' => 19.0, 'price_out' => 36.0];
        $rows[] = ['name' => 'Steigleitungen Piece', 'price_in' => 111.6, 'price_out' => 183.75];
        $rows[] = ['name' => 'Internal Anschlüsse16 mm Piece', 'price_in' => 12.78, 'price_out' => 20.7];
        $rows[] = ['name' => 'Internal Anschlüsse 20 mm Piece', 'price_in' => 17.26, 'price_out' => 38.2];
        $rows[] = ['name' => 'Externe Anschlüsse Sanipex 16mm Piece', 'price_in' => 8.45, 'price_out' => 17.6];
        $rows[] = ['name' => 'Externe Anschlüsse Sanipex 20mm Piece', 'price_in' => 12.0, 'price_out' => 25.0];
        $rows[] = ['name' => 'Externe Anschlüsse Sanipex  2x16mm Piece', 'price_in' => 15.79, 'price_out' => 32.9];
        $rows[] = ['name' => 'Externe Anschlüsse Sanipex 2x20mm Piece', 'price_in' => 25.44, 'price_out' => 53.0];
        $rows[] = ['name' => 'Externe Anschlüsse Sanipex 3x16mm Piece', 'price_in' => 22.46, 'price_out' => 46.8];
        $rows[] = ['name' => 'Externe Anschlüsse Sanipex 3x20mm Piece', 'price_in' => 36.0, 'price_out' => 75.0];
        $rows[] = ['name' => 'Externe Anschlüsse Sanipex 4x16mm Piece', 'price_in' => 31.58, 'price_out' => 65.8];
        $rows[] = ['name' => 'Externe Anschlüsse Sanipex 4x20mm Piece', 'price_in' => 50.88, 'price_out' => 106.0];
        $rows[] = ['name' => 'Externe Anschlüsse Sanipex 5x16mm Piece', 'price_in' => 38.25, 'price_out' => 79.7];
        $rows[] = ['name' => 'Externe Anschlüsse Sanipex 5x20mm Piece', 'price_in' => 61.44, 'price_out' => 128.0];
        $rows[] = ['name' => 'Externe Anschlüsse iFIT 16/20 mm Piece', 'price_in' => 12.61, 'price_out' => 19.7];
        $rows[] = ['name' => 'Externe Anschlüsse iFIT 2x16/20mm Piece', 'price_in' => 18.05, 'price_out' => 28.2];
        $rows[] = ['name' => 'Externe Anschlüsse iFIT 3x16/20mm Piece', 'price_in' => 22.4, 'price_out' => 35.0];
        $rows[] = ['name' => 'Externe Anschlüsse iFIT 4x16/20mm Piece', 'price_in' => 32.0, 'price_out' => 50.0];
        $rows[] = ['name' => 'Externe Anschlüsse iFIT 5x16/20mm Piece', 'price_in' => 40.45, 'price_out' => 63.2];
        $rows[] = ['name' => 'Externe Anschlüsse Nussbaum 16mm Piece', 'price_in' => 8.45, 'price_out' => 17.6];
        $rows[] = ['name' => 'Externe Anschlüsse Nussbaum 20mm Piece', 'price_in' => 12.0, 'price_out' => 25.0];
        $rows[] = ['name' => 'Externe Anschlüsse Nussbaum 2x16mm Piece', 'price_in' => 15.79, 'price_out' => 32.9];
        $rows[] = ['name' => 'Externe Anschlüsse Nussbaum 2x20mm Piece', 'price_in' => 25.44, 'price_out' => 53.0];
        $rows[] = ['name' => 'Externe Anschlüsse Nussbaum 3x16mm Piece', 'price_in' => 22.46, 'price_out' => 46.8];
        $rows[] = ['name' => 'Externe Anschlüsse Nussbaum 3x20mm Piece', 'price_in' => 36.75, 'price_out' => 75.0];
        $rows[] = ['name' => 'Externe Anschlüsse Nussbaum 4x16mm Piece', 'price_in' => 31.58, 'price_out' => 65.8];
        $rows[] = ['name' => 'Externe Anschlüsse Nussbaum 4x20mm Piece', 'price_in' => 50.88, 'price_out' => 106.0];
        $rows[] = ['name' => 'Externe Anschlüsse Nussbaum 5x16mm Piece', 'price_in' => 38.25, 'price_out' => 79.7];
        $rows[] = ['name' => 'Externe Anschlüsse Nussbaum 5x20mm Piece', 'price_in' => 61.44, 'price_out' => 128.0];
        $rows[] = ['name' => 'KQ-Wasserzählertstrecke Piece', 'price_in' => 102.0, 'price_out' => 150.0];
        $rows[] = ['name' => 'Freistehend Aufstock Piece', 'price_in' => 32.75, 'price_out' => 40.0];
        $rows[] = ['name' => 'Vorwand Aufstock Piece', 'price_in' => 21.84, 'price_out' => 30.0];
        $rows[] = ['name' => 'Kompakteinheit, Absperrventile 3/4" 1 Zählergehäuse Koax 2" Piece', 'price_in' => 200.0, 'price_out' => 410.0];
        $rows[] = ['name' => 'Kompakteinheit, Absperrventile 3/4"  2 Zählergehäuse Koax 2" Piece', 'price_in' => 225.0, 'price_out' => 453.0];
        $rows[] = ['name' => 'Kompakteinheit, Absperrventile 3/4" Ohne Zählergehäuse Piece', 'price_in' => 155.0, 'price_out' => 253.0];
        $rows[] = ['name' => 'Nische ca. 50cmx30cm (für  Dusche/Bad) Piece', 'price_in' => 15.0, 'price_out' => 30.0];
        $rows[] = ['name' => 'Nische für Spiegelschrank 80cm x 80cm Piece', 'price_in' => 25.0, 'price_out' => 50.0];
        $rows[] = ['name' => 'Freistehend Aufstock mit Seiten-Abschl. Piece', 'price_in' => 38.0, 'price_out' => 45.0];
        $rows[] = ['name' => 'Vorwand Aufstock mit Seiten-Abschl. Piece', 'price_in' => 25.0, 'price_out' => 36.0];
        $rows[] = ['name' => 'Vorwand Grundrahme Piece', 'price_in' => 20.0, 'price_out' => 75.0];
        $rows[] = ['name' => 'Vorwand Grundrahme Teilhoch Piece', 'price_in' => 25.0, 'price_out' => 90.0];
        $rows[] = ['name' => 'Vorwand Grundrahme Telihoch und Rahmhoch Piece', 'price_in' => 25.0, 'price_out' => 95.0];
        $rows[] = ['name' => 'Freistehend Grundrahme Piece', 'price_in' => 45.0, 'price_out' => 150.0];
        $rows[] = ['name' => 'Freistehend Grundrahme Hinten leer Piece', 'price_in' => 60.0, 'price_out' => 194.0];
        $rows[] = ['name' => 'Nische für Spiegelschrank 120cm x 80cm Piece', 'price_in' => 30.0, 'price_out' => 60.0];
        $rows[] = ['name' => 'Nische für Spiegelschrank 90cm x 60cm Piece', 'price_in' => 23.0, 'price_out' => 47.0];
        $rows[] = ['name' => 'Waschtisch UP Piece', 'price_in' => 70.0, 'price_out' => 90.0];
        $rows[] = ['name' => 'Isoliert mit schwer Schallschutzmatte Piece', 'price_in' => 31.02, 'price_out' => 65.64];
        $rows[] = ['name' => 'Deckeneinlagen WAS Piece', 'price_in' => 70.0, 'price_out' => 70.0];
        $rows[] = ['name' => 'Vorwand Grundelement DeBo Piece', 'price_in' => 60.0, 'price_out' => 194.0];
        $rows[] = ['name' => 'Vorwand Aufstockelement DeBo Piece', 'price_in' => 38.0, 'price_out' => 45.0];
        $rows[] = ['name' => 'Befestigung DeBo Piece', 'price_in' => 2.15, 'price_out' => 5.3];
        $rows[] = ['name' => 'Trennwand Grundelement DeBo Piece', 'price_in' => 2.15, 'price_out' => 194.0];
        $rows[] = ['name' => 'Trennwand Aufstockelement DeBo Piece', 'price_in' => 38.0, 'price_out' => 45.0];
        $rows[] = ['name' => 'GF-JRG UP-Absperr-/Zählereiheit kompakt 3/4\'\' -PN Piece', 'price_in' => 173.3, 'price_out' => 361.0];
        $rows[] = ['name' => 'Lüftungsgehäuse (Lieferung bauseits) Piece', 'price_in' => 20.0, 'price_out' => 40.0];
        $rows[] = ['name' => 'Inkl. Rohrschelle Piece', 'price_in' => 5.0, 'price_out' => 5.0];
        $rows[] = ['name' => 'Deckeneinlagen WAR Piece', 'price_in' => 92.5, 'price_out' => 92.5];
        $rows[] = ['name' => 'Fallstrang Umlenkung Geberit Isol. (90/ 110) Piece', 'price_in' => 45.0, 'price_out' => 60.0];
        $rows[] = ['name' => 'Inkl. E-Muffen Piece', 'price_in' => 1.0, 'price_out' => 1.0];
        $rows[] = ['name' => 'Inkl. Schalungsschoner Piece', 'price_in' => 1.0, 'price_out' => 1.0];
        $rows[] = ['name' => 'Inkl. Kanisparblöck Piece', 'price_in' => 1.0, 'price_out' => 1.0];
        $rows[] = ['name' => 'Tragschalle Piece', 'price_in' => 1.0, 'price_out' => 1.0];
        DB::table('material_pieces')->insert($rows);
    }
}
